; Sound Effects for song , version 2.0, generated by Arkos Tracker 2.

fx_SoundEffects
fx_SoundEffectsDisarkGenerateExternalLabel

; The sound effects, starting at 1.
fx_SoundEffectsDisarkPointerRegionStart0
	dw fx_SoundEffects_Sound1	; Sound effect 1.
	dw fx_SoundEffects_Sound2	; Sound effect 2.
	dw fx_SoundEffects_Sound3	; Sound effect 3.
	dw fx_SoundEffects_Sound4	; Sound effect 4.
	dw fx_SoundEffects_Sound5	; Sound effect 5.
	dw fx_SoundEffects_Sound6	; Sound effect 6.
	dw fx_SoundEffects_Sound7	; Sound effect 7.
	dw fx_SoundEffects_Sound8	; Sound effect 8.
fx_SoundEffectsDisarkPointerRegionEnd0

fx_SoundEffectsDisarkByteRegionStart1
; Sound effect 1.
fx_SoundEffects_Sound1
	db 0	; Speed

	db 61	; Soft only. Volume: 15.
	dw 475	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 387	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 337	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 274	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 261	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 224	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 211	; Software period.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

fx_SoundEffects_Sound1_Loop	db 0	; No soft, no hard. Volume: 0.

	db 12	; End of the sound effect.
fx_SoundEffectsDisarkPointerRegionStart2
	dw fx_SoundEffects_Sound1_Loop	; Loops here.
fx_SoundEffectsDisarkPointerRegionEnd2

; Sound effect 2.
fx_SoundEffects_Sound2
	db 0	; Speed

	db 61	; Soft only. Volume: 15.
	dw 158	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 163	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 163	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 178	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 183	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 194	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 204	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 214	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 204	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 194	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 183	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 178	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 173	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 194	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 204	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 214	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 224	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 234	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 229	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 214	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 204	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 194	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 189	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 209	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 219	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 234	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 244	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 254	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 254	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 239	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 224	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 214	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 204	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 204	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 239	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 254	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 269	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 284	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 284	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 269	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 601	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 601	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 153	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 123	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 98	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 83	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 68	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 63	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 58	; Software period.

	db 185	; Soft only. Volume: 14.
	db 1	; Noise: 1.
	dw 65534	; Software period.

	db 181	; Soft only. Volume: 13.
	db 1	; Noise: 1.
	dw 65534	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 601	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 601	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 123	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 103	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 83	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 73	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 63	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 58	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 53	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 65534	; Software period.

	db 29	; Soft only. Volume: 7.
	dw 65534	; Software period.

	db 9	; Soft only. Volume: 2.
	dw 65534	; Software period.

fx_SoundEffects_Sound2_Loop	db 0	; No soft, no hard. Volume: 0.

	db 12	; End of the sound effect.
fx_SoundEffectsDisarkPointerRegionStart3
	dw fx_SoundEffects_Sound2_Loop	; Loops here.
fx_SoundEffectsDisarkPointerRegionEnd3

; Sound effect 3.
fx_SoundEffects_Sound3
	db 0	; Speed

	db 61	; Soft only. Volume: 15.
	dw 244	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 269	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 304	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 354	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 415	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 495	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 65534	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 65534	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 1232	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 65534	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 65534	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 495	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 415	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 354	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 309	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 274	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 244	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 219	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 199	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 189	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 65534	; Software period.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

fx_SoundEffects_Sound3_Loop	db 0	; No soft, no hard. Volume: 0.

	db 12	; End of the sound effect.
fx_SoundEffectsDisarkPointerRegionStart4
	dw fx_SoundEffects_Sound3_Loop	; Loops here.
fx_SoundEffectsDisarkPointerRegionEnd4

; Sound effect 4.
fx_SoundEffects_Sound4
	db 0	; Speed

	db 177	; Soft only. Volume: 12.
	db 1	; Noise: 1.
	dw 65534	; Software period.

	db 181	; Soft only. Volume: 13.
	db 1	; Noise: 1.
	dw 65534	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 616	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 490	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 405	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 314	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 304	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 244	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 229	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 204	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 183	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 168	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 158	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 143	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 133	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 123	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 123	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 113	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 108	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 103	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 98	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 93	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 93	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 83	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 83	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 78	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 78	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 65534	; Software period.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

fx_SoundEffects_Sound4_Loop	db 0	; No soft, no hard. Volume: 0.

	db 12	; End of the sound effect.
fx_SoundEffectsDisarkPointerRegionStart5
	dw fx_SoundEffects_Sound4_Loop	; Loops here.
fx_SoundEffectsDisarkPointerRegionEnd5

; Sound effect 5.
fx_SoundEffects_Sound5
	db 0	; Speed

	db 61	; Soft only. Volume: 15.
	dw 123	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 123	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 133	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 138	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 148	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 163	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 178	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 199	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 219	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 249	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 269	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 264	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 239	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 209	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 189	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 173	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 163	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 148	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 138	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 128	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 123	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 123	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 128	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 138	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 148	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 158	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 173	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 194	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 214	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 239	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 264	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 269	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 249	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 219	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 194	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 178	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 163	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 148	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 138	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 133	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 123	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 123	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 128	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 138	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 148	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 158	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 173	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 189	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 209	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 239	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 264	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 269	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 249	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 219	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 199	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 183	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 168	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 153	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 143	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 133	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 123	; Software period.

	db 13	; Soft only. Volume: 3.
	dw 123	; Software period.

	db 9	; Soft only. Volume: 2.
	dw 123	; Software period.

fx_SoundEffects_Sound5_Loop	db 0	; No soft, no hard. Volume: 0.

	db 12	; End of the sound effect.
fx_SoundEffectsDisarkPointerRegionStart6
	dw fx_SoundEffects_Sound5_Loop	; Loops here.
fx_SoundEffectsDisarkPointerRegionEnd6

; Sound effect 6.
fx_SoundEffects_Sound6
	db 0	; Speed

	db 8	; No soft, no hard. Volume: 1.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

fx_SoundEffects_Sound6_Loop	db 0	; No soft, no hard. Volume: 0.

	db 12	; End of the sound effect.
fx_SoundEffectsDisarkPointerRegionStart7
	dw fx_SoundEffects_Sound6_Loop	; Loops here.
fx_SoundEffectsDisarkPointerRegionEnd7

; Sound effect 7.
fx_SoundEffects_Sound7
	db 0	; Speed

	db 49	; Soft only. Volume: 12.
	dw 462	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 513	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 374	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 286	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 173	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 123	; Software period.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

	db 0	; No soft, no hard. Volume: 0.

fx_SoundEffects_Sound7_Loop	db 0	; No soft, no hard. Volume: 0.

	db 12	; End of the sound effect.
fx_SoundEffectsDisarkPointerRegionStart8
	dw fx_SoundEffects_Sound7_Loop	; Loops here.
fx_SoundEffectsDisarkPointerRegionEnd8

; Sound effect 8.
fx_SoundEffects_Sound8
	db 0	; Speed

	db 61	; Soft only. Volume: 15.
	dw 418	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 418	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 418	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 418	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 418	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 418	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 418	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 418	; Software period.

	db 29	; Soft only. Volume: 7.
	dw 418	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 418	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 418	; Software period.

	db 17	; Soft only. Volume: 4.
	dw 418	; Software period.

	db 13	; Soft only. Volume: 3.
	dw 418	; Software period.

	db 9	; Soft only. Volume: 2.
	dw 418	; Software period.

fx_SoundEffects_Sound8_Loop	db 5	; Soft only. Volume: 1.
	dw 418	; Software period.

	db 4	; End of the sound effect.

fx_SoundEffectsDisarkByteRegionEnd1
